# Generated by Django 4.2.5 on 2023-09-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=300)),
                ('store_description', models.CharField(max_length=300)),
                ('store_cover_image', models.CharField(max_length=300)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
        ),
    ]
