# Generated by Django 5.0.1 on 2024-02-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=225, null=True)),
                ('store_description', models.CharField(blank=True, max_length=225, null=True)),
                ('store_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
