# Generated by Django 5.0.1 on 2024-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_description',
            field=models.CharField(default='Enter Store Description', max_length=225),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='Enter Store Name', max_length=225),
        ),
    ]
