# Generated by Django 5.0.1 on 2024-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_store_description_alter_store_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
