# Generated by Django 4.2.4 on 2023-12-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_galleries', '__first__'),
        ('user_profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleTertiaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
                ('product_sizes', models.CharField(max_length=250)),
                ('product_colours', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_galleries.femaletertiarygallery')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FemaleSecondaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
                ('product_sizes', models.CharField(max_length=250)),
                ('product_colours', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_galleries.femalesecondarygallery')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FemaleQuaternaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
                ('product_sizes', models.CharField(max_length=250)),
                ('product_colours', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_galleries.femalequaternarygallery')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FemalePrimaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
                ('product_sizes', models.CharField(max_length=250)),
                ('product_colours', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_galleries.femaleprimarygallery')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
