# Generated by Django 4.2.5 on 2023-09-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryproduct',
            name='store_gallery_id',
        ),
        migrations.AddField(
            model_name='primaryproduct',
            name='content_type',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primaryproduct',
            name='object_id',
            field=models.PositiveIntegerField(default='Null'),
            preserve_default=False,
        ),
    ]
