# Generated by Django 4.2.4 on 2023-12-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '__first__'),
        ('store_galleries', '__first__'),
        ('store_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FemalePrimaryProduct',
            new_name='PrimaryProduct',
        ),
        migrations.RenameModel(
            old_name='FemaleSecondaryProduct',
            new_name='QuaternaryProduct',
        ),
        migrations.RenameModel(
            old_name='FemaleTertiaryProduct',
            new_name='SecondaryProduct',
        ),
        migrations.RenameModel(
            old_name='FemaleQuaternaryProduct',
            new_name='TertiaryProduct',
        ),
        migrations.AlterField(
            model_name='quaternaryproduct',
            name='gallery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_galleries.femalequaternarygallery'),
        ),
        migrations.AlterField(
            model_name='secondaryproduct',
            name='gallery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_galleries.femalesecondarygallery'),
        ),
        migrations.AlterField(
            model_name='tertiaryproduct',
            name='gallery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_galleries.femaletertiarygallery'),
        ),
    ]
