# Generated by Django 5.0.1 on 2024-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_merchant_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
