# Generated by Django 5.0.1 on 2024-02-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_customer_email_customer_groups_customer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='user_permissions',
        ),
    ]
