# Generated by Django 5.0.1 on 2024-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_customer_email_merchant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='at_user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_merchant',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='at_merchant',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_merchant',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_description',
            field=models.CharField(default='no-description', max_length=500),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user_bio',
            field=models.CharField(default='no-bio', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_bio',
            field=models.CharField(default='no-bio', max_length=500),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='store_description',
            field=models.CharField(default='no-description', max_length=500),
        ),
    ]
