# Generated by Django 5.0.1 on 2024-02-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_customer_groups_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_staff',
            new_name='is_merchant',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='is_active',
            new_name='is_merchant',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='user_permissions',
        ),
    ]
