# Generated by Django 5.0.1 on 2024-02-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_rename_is_staff_customer_is_merchant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='store_name',
        ),
    ]
