# Generated by Django 5.0.1 on 2024-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_rename_at_store_merchant_at_merchant_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(default='no-username', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user_name',
            field=models.CharField(default='no-username', max_length=100),
        ),
    ]
