# Generated by Django 5.0.1 on 2024-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_customer_user_name_merchant_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='background_picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='background_picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='profile_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
