# Generated by Django 5.0.1 on 2024-02-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0010_alter_customer_background_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='user',
        ),
    ]
