# Generated by Django 5.0.1 on 2024-02-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCollection',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('collection_title', models.CharField(blank=True, max_length=150, null=True)),
                ('collection_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryCollection',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('collection_title', models.CharField(blank=True, max_length=150, null=True)),
                ('collection_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryCollection',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('collection_title', models.CharField(blank=True, max_length=150, null=True)),
                ('collection_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TertiaryCollection',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('collection_title', models.CharField(blank=True, max_length=150, null=True)),
                ('collection_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
