# Generated by Django 5.0.1 on 2024-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercollection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='primarycollection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secondarycollection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tertiarycollection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
