# Generated by Django 4.2.4 on 2023-12-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercollection',
            name='collection_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='primarycollection',
            name='collection_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secondarycollection',
            name='collection_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tertiarycollection',
            name='collection_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customercollection',
            name='collection_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='primarycollection',
            name='collection_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='secondarycollection',
            name='collection_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tertiarycollection',
            name='collection_title',
            field=models.CharField(max_length=150),
        ),
    ]
