# Generated by Django 5.0.1 on 2024-02-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercollection',
            name='collection_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customercollection',
            name='collection_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='primarycollection',
            name='collection_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='primarycollection',
            name='collection_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='secondarycollection',
            name='collection_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='secondarycollection',
            name='collection_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tertiarycollection',
            name='collection_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tertiarycollection',
            name='collection_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
