# Generated by Django 4.2.5 on 2023-09-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSecondaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tertiary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.tertiarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPrimaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tertiary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.tertiarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='MaleTertiaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secondary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.secondarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='MaleSecondaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secondary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.secondarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='MaleQuaternaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secondary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.secondarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='MalePrimaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secondary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.secondarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleTertiaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.primarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleSecondaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.primarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleQuaternaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.primarycollection')),
            ],
        ),
        migrations.CreateModel(
            name='FemalePrimaryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_subtitle', models.CharField(max_length=300)),
                ('gallery_image', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.primarycollection')),
            ],
        ),
    ]
