# Generated by Django 5.0.1 on 2024-03-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_collections', '0001_initial'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
                ('product_sizes', models.CharField(max_length=250)),
                ('product_colours', models.CharField(max_length=250)),
                ('feature_list', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.primarycollection')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
                ('product_sizes', models.CharField(max_length=250)),
                ('product_colours', models.CharField(max_length=250)),
                ('feature_list', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.secondarycollection')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TertiaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
                ('product_sizes', models.CharField(max_length=250)),
                ('product_colours', models.CharField(max_length=250)),
                ('feature_list', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_collections.tertiarycollection')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
