# Generated by Django 4.2.4 on 2023-12-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryproduct',
            name='feature_list',
            field=models.BigIntegerField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='secondaryproduct',
            name='feature_list',
            field=models.BigIntegerField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='tertiaryproduct',
            name='feature_list',
            field=models.BigIntegerField(max_length=1000000, null=True),
        ),
    ]
