# Generated by Django 5.0.1 on 2024-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryproduct',
            name='product_image',
            field=models.ImageField(blank=True, default='../default_images/fabrice-villard-Jrl_UQcZqOc-unsplash.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='secondaryproduct',
            name='product_image',
            field=models.ImageField(blank=True, default='../default_images/fabrice-villard-Jrl_UQcZqOc-unsplash.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tertiaryproduct',
            name='product_image',
            field=models.ImageField(blank=True, default='../default_images/fabrice-villard-Jrl_UQcZqOc-unsplash.jpg', null=True, upload_to='images/'),
        ),
    ]
